package View;

import Controller.IMG;
import javax.swing.JOptionPane;
import jdbc.ConnectionTest;

/**
 *
 * @author DevL
 */
public class Menu extends javax.swing.JFrame {

    ConnectionTest testeconexao = new ConnectionTest();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        showIcon();
    }

    public void showIcon() {
        IMG imagem = new IMG();
        imagem.showIcon(lblimage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        BtnLogoff = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelid4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(640, 520));
        setPreferredSize(new java.awt.Dimension(640, 520));
        setSize(getPreferredSize());
        getContentPane().setLayout(null);

        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(470, 160, 110, 30);

        lblimage.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(lblimage);
        lblimage.setBounds(40, 150, 380, 210);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar);
        btnListar.setBounds(470, 260, 110, 30);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(470, 210, 110, 30);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(470, 310, 110, 30);

        BtnLogoff.setText("Deslogar");
        BtnLogoff.setPreferredSize(new java.awt.Dimension(34, 24));
        BtnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoffActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogoff);
        BtnLogoff.setBounds(470, 360, 110, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelid4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelid4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelid4.setText("Menu");
        jPanel1.add(labelid4);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (testeconexao.testandoconexao()) {
            JtableEditUser telaEdit = new JtableEditUser();
            this.dispose();
            telaEdit.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try{
            JtableShowUser telaListUser = new JtableShowUser();
            this.dispose();
            telaListUser.setVisible(true);
        }catch (Exception excecao) {
            // Lida com a exceção
            JOptionPane.showMessageDialog(null, "O banco de dados está offline ! ");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        /*
        try{
            RegisterUser telaregister = new RegisterUser();
            this.dispose();
            telaregister.setVisible(true);
        } catch (Exception excecao) {
            // Lida com a exceção
            JOptionPane.showMessageDialog(null, "O banco de dados está offline ! ");
        }
        */
        if (testeconexao.testandoconexao()) {
            RegisterUser telaregister = new RegisterUser();
            this.dispose();
            telaregister.setVisible(true);
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void BtnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoffActionPerformed
        Start_App telalogin = new Start_App();
         this.dispose();
         telalogin.setVisible(true);
    }//GEN-LAST:event_BtnLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogoff;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelid4;
    private javax.swing.JLabel lblimage;
    // End of variables declaration//GEN-END:variables
}
