package View;

import Controller.IMG;
import Controller.ListTable;
import Model.Test;
import Dao.TestDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Jdbc.ConnectionTest;

/**
 * @author DevL
 */
public class JtableEditTest extends javax.swing.JFrame {
    TestDao dao;
    ConnectionTest testeconexao = new ConnectionTest();

    private void clearField() {
        txtId.setText("");
        txtStudent.setText("");
        txtProfessor.setText("");
        txtGrade.setText("");
        txtSubject.setText("");
        
    }

    private void listTable() {
        
        //nem acredito que deu certo kkkk 
        if (testeconexao.testandoconexao()) {
            ListTable listtable = new ListTable();
            dao = new TestDao();
            ArrayList<Test> list = dao.listTests();
            listtable.fillTable(list, VarTabelaView);
            validateButtons();
        }
    }

    public void showIcon() {
        IMG imagem = new IMG();
        imagem.showIcon(lblimage);
    }

    private void validateButtons() {
        int rowCount = VarTabelaView.getRowCount();

        if (rowCount > 0) {
            BtnEdit.setEnabled(true);
            BtnDelete.setEnabled(true);
        } else {
            BtnEdit.setEnabled(false);
            BtnDelete.setEnabled(false);
        }
    }

    /**
     * Creates new form Jtable
     */
    public JtableEditTest() {

        initComponents();
        this.setLocationRelativeTo(null);
        listTable();
        showIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelid4 = new javax.swing.JLabel();
        txtGrade1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtProfessor = new javax.swing.JTextField();
        labelid = new javax.swing.JLabel();
        BtnDelete = new javax.swing.JButton();
        txtStudent = new javax.swing.JTextField();
        BtnEdit = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        labelid1 = new javax.swing.JLabel();
        labelid3 = new javax.swing.JLabel();
        labelid2 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VarTabelaView = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        txtGrade = new javax.swing.JTextField();
        labelid5 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        labelid4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid4.setText("Nota");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        setSize(new java.awt.Dimension(650, 520));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid.setText("ID");

        BtnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnDelete.setText("Excluir");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEdit.setText("Salvar");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        txtId.setEditable(false);

        labelid1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid1.setText("Professor");

        labelid3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid3.setText("Nota");

        labelid2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid2.setText("Estudante");

        txtFilter.setToolTipText("");
        txtFilter.setName(""); // NOI18N

        btnFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setToolTipText("");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        VarTabelaView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VarTabelaView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estudante", "Professor", "Nota", "Matéria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VarTabelaView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VarTabelaViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VarTabelaView);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        labelid5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelid5.setText("Matéria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelid2)
                                    .addComponent(labelid1))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtId)
                                        .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelid3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelid5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelid)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelid2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelid1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelid3)
                            .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelid5)
                            .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEdit)
                            .addComponent(BtnDelete)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        if (testeconexao.testandoconexao()) {
            if (txtStudent.getText().isEmpty() || txtProfessor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null, "Selecione uma Prova primeiro.");
            } else {
                try {
                    dao = new TestDao();
                    Test obj = new Test();
                    int id = Integer.parseInt(txtId.getText());
                    obj.setTest(id, txtStudent.getText(), txtProfessor.getText(),
                            Float.parseFloat(txtGrade.getText()),txtSubject.getText());
                    dao.deleteTest(obj);
                    clearField();
                    listTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(
                            null, "Erro! \n" + e);
                }
            }
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed

        if (testeconexao.testandoconexao()) {
            if (VarTabelaView.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma Prova para editar.");
                return;
            }
            
            if (txtStudent.getText().isEmpty() || txtProfessor.getText().isEmpty()
                ||txtGrade.getText().isEmpty() || txtSubject.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null, "Selecione uma Prova primeiro.");
            } else {
                try {
                    Test obj = new Test();
                    int id = Integer.parseInt(txtId.getText());
                   obj.setTest(id, txtStudent.getText(), txtProfessor.getText(),
                            Float.parseFloat(txtGrade.getText()),txtSubject.getText());

                    dao = new TestDao();
                    dao.editTest(obj);

                    clearField();
                    listTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(
                            null, "Erro! \n" + e);
                }
            }
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        if (testeconexao.testandoconexao()) {
            dao = new TestDao();
            String fieldresearch = txtFilter.getText();
            ListTable listtable = new ListTable();
            ArrayList<Test> lista = dao.filterTest(fieldresearch);
            listtable.fillTable(lista, VarTabelaView);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void VarTabelaViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VarTabelaViewMouseClicked
        txtId.setText(VarTabelaView.getValueAt(VarTabelaView.getSelectedRow(), 0).toString());
        txtStudent.setText(VarTabelaView.getValueAt(VarTabelaView.getSelectedRow(), 1).toString());
        txtProfessor.setText(VarTabelaView.getValueAt(VarTabelaView.getSelectedRow(), 2).toString());
        
        txtGrade.setText(VarTabelaView.getValueAt(VarTabelaView.getSelectedRow(), 3).toString());
        txtSubject.setText(VarTabelaView.getValueAt(VarTabelaView.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_VarTabelaViewMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu menuScreen = new Menu();
        this.dispose();
        menuScreen.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JtableEditTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JtableEditTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JtableEditTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JtableEditTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JtableEditTest().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JTable VarTabelaView;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelid1;
    private javax.swing.JLabel labelid2;
    private javax.swing.JLabel labelid3;
    private javax.swing.JLabel labelid4;
    private javax.swing.JLabel labelid5;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtGrade1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProfessor;
    private javax.swing.JTextField txtStudent;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
